services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ApiDB
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      # Esto es para inicializar la db de prueba pobladaxd 
      - ./users_api/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - mi_red
  
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
    networks:
      - mi_red
  
  logs_api:
    build:
      context: ./logs_api
    ports:
      - "5005:5005"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_SERVICE: rabbitmq
      SERVICE_NAME: logs_api
    volumes:
      - ./logs_api:/app
    networks:
      - mi_red
    tty: true

  users_api:
    build:
      context: ./users_api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      SERVICE: mysql
      USER: root
      PASSWORD: root_password
      DATABASE: ApiDB
      RABBITMQ_SERVICE: rabbitmq
      SERVICE_NAME: users_api
      SECRET_KEY: microcevichesecretkey@2011
    volumes:
      # Monta la carpeta local en el contenedor
      - ./users_api:/app
    networks:
      - mi_red

networks:
  mi_red:
