services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ApiDB
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      # Esto es para inicializar la db de prueba pobladaxd 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - mi_red
  
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
    networks:
      - mi_red

  consumidor:
    build:
      context: ./message-service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_SERVICE: rabbitmq
    volumes:
      - ./message-service:/service
    networks:
      - mi_red
    tty: true

  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      SERVICE: mysql
      USER: root
      PASSWORD: root_password
      DATABASE: ApiDB
      RABBITMQ_SERVICE: rabbitmq
      SERVICE_NAME: api
      SECRET_KEY: microcevichesecretkey@2011
    volumes:
      # Monta la carpeta local en el contenedor
      - ./api:/app
    networks:
      - mi_red

networks:
  mi_red:
