services:
  users_db_mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: users_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./users_api/init.sql:/docker-entrypoint-initdb.d/init.sql 
    restart: always
    networks:
      - system_network
  
  profiles_db_mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: profiles_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./profiles_api/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - system_network
  
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
    restart: always
    networks:
      - system_network
  
  logs_api:
    build:
      context: ./logs_api
    ports:
      - "5005:5005"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_SERVICE: rabbitmq
      SERVICE_NAME: logs_api
    volumes:
      - ./logs_api:/app
    networks:
      - system_network
    restart: always
    tty: true

  users_api:
    build:
      context: ./users_api
    ports:
      - "5000:5000"
    depends_on:
      - users_db_mysql
      - rabbitmq
    environment:
      SERVICE: users_db_mysql
      USER: root
      PASSWORD: root_password
      DATABASE: users_db
      RABBITMQ_SERVICE: rabbitmq
      SERVICE_NAME: users_api
      SECRET_KEY: microcevichesecretkey@2011
    volumes:
      - ./users_api:/app
    restart: always
    networks:
      - system_network
  
  profiles_api:
    build:
      context: ./profiles_api
    ports:
      - "4000:4000"
    depends_on:
      - profiles_db_mysql
      - users_api
    environment:
      MYSQL_SERVICE: profiles_db_mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_DATABASE: profiles_db
      RABBITMQ_SERVICE: rabbitmq
      SERVICE_NAME: profiles_api
      SECRET_KEY: microcevichesecretkey@2011
    volumes:
      - ./profiles_api:/app
    restart: always
    networks:
      - system_network

networks:
  system_network:
