openapi: 3.0.0
info:
  title: Flask Logs API
  description: API for logs management
  version: 1.0.0

servers:
  - url: http://localhost:5005
    description: Development server

paths:
  /logs:
    get:
      summary: Get All Logs
      responses:
        '200':
          description: List of logs
          content:
            application/json:
              example:
                page: 1
                per_page: 10
                search_name: John
                users:
                  schema:
                    $ref: './schemas/FullLogs.json'
              schema:
                $ref: './schemas/FullLogs.json''
        '500':
          description: Error al obtener los logs de aplicacion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'

    post:
      summary: Register a new log
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Logs'
      responses:
        '201':
          description: Usuario registrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '400':
          description: El campo es requerido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '500':
          description: Error al registrar usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
      
  /logs/{application}:
    get:
      summary: Get logs by application
      parameters:
        - name: application
          in: path
          required: true
          description: name of application
          schema:
            type: string
            maxLength: 100
      responses:
        '200':
          description: logs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Full-Logs'
        '404':
          description: La aplicacion no encuentra logs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '500':
          description: Error al obtener los logs de aplicacion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'

  /health:
    get:
      summary: Verificar el estado de la API
      responses:
        '200':
          description: La API está en funcionamiento
        '503':
          description: La API no está disponible
          content:
            application/json:
              example:
                status: "Service Unavailable"
        default:
          description: Respuesta por defecto
          content:
            application/json:
              example:
                status: "Unknown"
security:
  - bearerAuth: []

components:
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    Full-Logs:
      $ref: './schemas/FullLogs.json'
    String:
      $ref: './schemas/String.json'
    CodigoHTTP:
      $ref: './schemas/Codigo-HTTP.json'
    Logs:
      $ref: './schemas/Logs.json'
    Token:
      $ref: './schemas/Token.json'


        

      


  

