openapi: 3.0.0
info:
  title: Profiles API
  description: API for Profiles management
  version: 1.0.0

servers:
  - url: http://localhost:4000
    description: Development server

paths:
  /profiles:
    get:
      summary: Get all Profiles
      parameters:
        - name: page
          in: query
          description: "Page number for pagination (default: 1)"
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 1000
            format: int32
        - name: per_page
          in: query
          description: "Number of items per page (default: 10)"
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 1000
            format: int32
        - name: search_id
          in: query
          description: "Search filter by id (default: ' ')"
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: List of Profiles
          content:
            application/json:
              example:
                page: 1
                per_page: 10
                search_id: 1
                users:
                  schema:
                    $ref: './schemas/Full-Profiles.json'
              schema:
                $ref: './schemas/Paginado.json'          
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '404':
          description: List of users
          content:
            application/json:
              example:
                page: 1
                per_page: 10
                search_name: Patricia
                users:
              schema:
                $ref: '#/components/schemas/Paginado'                  
        '500':
          description: Error al registrar usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'  

    post:
      summary: Create profiles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Create-profiles'
      responses:
        '201':
          description: Perfil registrado
          content:
            application/json:
              schema:
                $ref: './schemas/Codigo-HTTP.json'
        '401':
          description: Credenciales invalidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '404':
          description: id no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '500':
          description: Error al crear perfil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP' 

  /profiles/{profile_id}:
    get:
      summary: get profiles by ID
      security:
        - BearerAuth: []
      parameters:
        - name: Profiles_id
          in: path
          required: true
          description: ID of the user to retrieve
          schema:
            type: integer
            minimum: 0
            maximum: 1000
            format: int32
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: './schemas/Full-Profiles.json'
        '401':
          description: Token invalido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '404':
          description: Perfil no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '500':
          description: Error al obtener el perfil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
    put:
      summary: Update profiles
      requestBody:
        required: true
        content:
          application/json:
            schema:  
              $ref: './schemas/Full-Profiles.json'
      responses:
        '200':
          description: Profile update successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '401':
          description: Credenciales invalidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '500':
          description: Error al actualizar el usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
    delete:
      summary: Eliminar un perfil por ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID del perfil a eliminar
          schema:
            type: integer
            minimum: 0
            format: int32
      responses:
        '200':
          description: Profile update successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '500':
          description: Error al actualizar el usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '401':
          description: Credenciales invalidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CodigoHTTP'
  /health:
    get:
      summary: Verificar el estado de la API
      responses:
        '200':
          description: La API está en funcionamiento
        '503':
          description: La API no está disponible
          content:
            application/json:
              example:
                status: "Service Unavailable"
        default:
          description: Respuesta por defecto
          content:
            application/json:
              example:
                status: "Unknown"
security:
  - bearerAuth: []

components:
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    Full-User:
      $ref: './schemas/Full-Profiles.json'
    String:
      $ref: './schemas/String.json'
    CodigoHTTP:
      $ref: './schemas/Codigo-HTTP.json'
    Paginado:
      $ref: './schemas/Paginado.json'  
    Create-profiles:
      $ref: './schemas/CreateProfiles.json'       